- repo_data/distribution.xml
The lapack headers are now provided by openblas so that packages will build against openblas rather than the unoptimized lapack implementation. Nothing links against it anymore :D
```
Package found in Unstable repository:
Name                : lapack, version: 3.6, release: 1
Summary             : Basic Linear Algebra Subprograms
Description         : Basic Linear Algebra Subprograms
Licenses            : BSD-3-Clause
Component           : programming
Dependencies        : gfortran glibc libgcc 
Distribution        : Solus, Dist. Release: 1
Architecture        : x86_64, Installed Size: 6.27 MB, Package Size: 1.89 MB
Reverse Dependencies: lapack-devel
```
> Deprecate lapack

- repo_data/distribution.xml
There is also qt5-translations package. But I have a new package for that, so will just make it release 23 to compensate. Shouldn't impact on any of the pkgconfig stuff.
> Deprecate old qt5 package names

- repo_data/components.xml
List:
- office.notes: There is a plethora of note-taking applications in the repository, ranging from gnome-todo to QOwnNotes.
- office.viewers: We have a variety of e-book and PDF viewing applications and it would be valuable to have them in a dedicated space.
- programming.haskell: Because oh god is there a lot of them in `programming`.
- programming.library: There currently is no place to put "generic" programming libraries. Just do a search via `eopkg search lib` and it starts to explain the siutation.
Note: "Why is there looking like a change for a couple components?" - They were using spaces, whereas the rest uses tabs, so I fixed that.
> Expanded list of components.

- eopkg_assist/backend.py
- solus_sc/thirdparty.py
Added the following to Third Party's UX:
- Bitwig Studio
- Enpass
- Flash Player (NPAPI)
- Flash Player (PPAPI)
- Google Earth
- Insync
- Mendeley Desktop
- Moneydance
> New inclusions in Third Party UX.

- repo_data/distribution.xml
Have moved the libs and devel to audacious-libs{,-devel}
Needs to be deprecated before it can be completed as it pulls in audacious-devel before audacious-libs-devel.
> Mark audacious-devel as obsolete

- solus_update/application.py
Last parameter was missing in Notify::add_action, which would be a parameter passed to the callback - which we don't make use of. Due to that the SC didn't open on button press.
Resulted in the error:
```
~/solus/solus-sc $ ./solus-update-checker
TypeError: action_show_updates() takes exactly 4 arguments (3 given)
```
> Fix #T2697: action_show_updates takes no extra parameters

- app_crap.py
- solus_sc/details.py
- solus_sc/package_view.py
- solus_sc/search_results.py
This change set requires appstream-glib 0.5.0 or greater. The (unused) _len arguments were removed from appstream-glib in 0.5.0.
Also, simplify `markup_convert(..., As.MarkupConvertFormat.SIMPLE)` to `markup_convert_simple(...)` instead.
> Update for appstream-glib 0.5+

- solus_sc/main_window.py
Side note: flake8 is being flaky about a repeated key
```solus_sc/components.py:31:5: F601 dictionary key 'multimedia.graphics' repeated with different values```
```solus_sc/components.py:34:5: F601 dictionary key 'multimedia.graphics' repeated with different values```
> Added Ctrl + F Search (fixes #70)

- repo_data/components.xml.in
Fixed typo in <_LocalName> for xorg.apps component
> Typo: Aplications -> Applications

- solus_sc/appsystem.py
Noticable for some app icons and the package-x-generic icon when using Adwaita. Resolves [T3380](https://dev.solus-project.com/T3380).
> Ensure we enforce 64x64 by scaling when necessary.

- repo_data/distribution.xml.in
I was trying to use these packages in the repo, no dice. Built the combined lib and bam, no issues....they were never used by anything (including as a rundep for x2goserver).
> repo_data: Obsolete split nx packages in favour of nx-libs

- repo_data/components.xml.in
Too many "- Core System"'s spoil the software center
> repo_data: Fix desktop.kde description

- solus_sc/thirdparty.py
After some testing with Papirus Icon Theme, I discovered that some Third Party applications were not name as accurately as possible, and while some items such as GitKraken did not exist at the time of inclusion (or at least, to my knowledge) and thus added by applying similar icons like web-github, such icons have been added to Moka since then.
I've validated that the icons being changed do have corresponding icons in Moka (list below), the default icon theme, thus this update should not affect existing users. I've also opened up PapirusDevelopmentTeam/papirus-icon-theme#515 to hopefully get a Moneydance icon landed and thus complete Third Party (as it currently stands) for SC.
- `/usr/share/icons/Moka/64x64/apps/gitkraken.png`
- `/usr/share/icons/Moka/64x64/web/google-earth.png`
- …
> Fix incorrect icon names for some Third Party applications.

- repo_data/components.xml.in
With packaging ruby gems (to avoid file conflicts), this will really need its
own component.
> repo_data: Add programming.ruby component

- repo_data/distribution.xml.in
Moving the gfortran libs into its own libgfortran packages results in a name
change for the 32bit package.
> repo: deprecate gfortran-32bit

- repo_data/distribution.xml.in
Peerunity is being replaced with the official Peercoin client. This is due to the fact that Peerunity work has since been merged into Peercoin and there has been changes made to Peercoin's blockchain that require use of a 0.6 or above client.
> Peerunity is being replaced with Peercoin.

- repo_data/distribution.xml.in
python3-xlib and python-xlib have the same source, so let's merge them
> repo: Deprecate python3-xlib, now part of python-xlib

- repo_data/distribution.xml.in
> repo: deprecate python3-decorator

- repo_data/distribution.xml.in
Proposal to deprecate pacifica-icon-theme for the reason that it's a dead upstream, with no release tarballs or activity in years. LaunchPad hasn't seen an update in 221 weeks and in fact I had originally created an issue back when I used Ubuntu **14.04 Trusty** (see https://github.com/fsvh/pacifica-icon-theme/issues/5) about support, which was never something that had occurred (and another issue about icon request was never responded to: https://github.com/fsvh/pacifica-icon-theme/issues/4).
> Deprecate captiva and pacifica icon themes.

- repo_data/distribution.xml.in
xsd now builds with internal versions and is exactly the same size
> Deprecate libcutl as it can't build against against modern libboost

- repo_data/distribution.xml.in
> Deprecate skrooge-devel package as it's no longer built

- repo_data/distribution.xml.in
> repo_data: Deprecate qupzilla and qupzilla-devel

- repo_data/distribution.xml.in
Combines multiple PRs into an easily mergeable (and non-conflicting) PR.
Deprecates:
- flat-plat-gtk-themes
- yubikey-neo-manager
- pycrypto
- rfkill
- Orphaned -devel packages
- lwqq and piding-lwqq
- autotrace
> Deprecate many packages from Solus

- repo_data/distribution.xml.in
Essential for getting a usable (and accurately named) tweak tool during GNOME stack upgrade. GNOME Tweaks is 3.28.1, whereas gnome-tweak-tool is locked at 3.26 and does not function with stack upgrade.
> Replace GNOME Tweak Tool with GNOME Tweaks.

- repo_data/distribution.xml.in
Qt4 deprecations as part of T6074 as well as misc libykneomgr deprecation.
Signed-off-by: Joey Riches <josephriches@gmail.com>
> Drop Qt4 from qca and qscintilla packages, deprecate libykneomgr and qjson

- README.md
- solus_sc/changelog.py
- solus_sc/details.py
- xng/util/markdown.py
Noticed the old URIs in the Software Center changelogs and stumbled upon the other outdated things while fixing them.
> Update URIs to getsol.us and fix appstream-data installation in README
